### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by cattyngmd** [GuFFy12/Discord-Token-Checker#3]
python 👎 
fix it

**Comment by GuFFy12** [comment]
Node js soon

**Comment by C4illin** [comment]
Why the python hate :(

**Comment by cattyngmd** [comment]
it looks like shit (snake_case) and its slow as fuck

**Comment by C4illin** [comment]
Better than kebab-case :)
Is node.js faster?

**Comment by cattyngmd** [comment]
> Better than kebab-case :)
worse than camelCase
> Is node.js faster?
yep, it is

**Comment by GuFFy12** [comment]
NODE JS https://github.com/amfero/DiscordTokenChecker 
I will contribute here
