### ISSUE TITLE
Would you like to write a script that parses all your friends and sends them a specific message?

### ISSUE THREAD

**Issue by Toxenskiy** [GuFFy12/Discord-Token-Checker#4]
You made a very cool script. You can also, for example, parse and send messages to all user correspondence.

**Comment by GuFFy12** [comment]
Hmm, that sounds good. For now i am trying to combine https://github.com/GuFFy12/Discord-Token-Parser and this checker. In new version I will add script that does this.

**Comment by GuFFy12** [comment]
hmmm i found api to get all users friends, but i cant find api to get all user correspondence. 
I'll try to search again

**Comment by GuFFy12** [comment]
it was worth looking better) here is the api to get all users from you corresponded /api/v7/users/@me/channels

**Comment by Toxenskiy** [comment]
Yes, I was looking for her too and for a very long time. Now I'm looking for a way to check if you can post in the channel.
