### ISSUE TITLE
Token stealing

### ISSUE THREAD

**Issue by SammyWhamy** [GuFFy12/Discord-Token-Checker#9]
Why would you need to send the token to your own closed source backend server to "check" it?

Simply do a request to `https://discord.com/api/users/@me` with `Authorization: Bot {token}`
On 200, it's a valid bot token
On 401 -> do a request to `https://discord.com/api/users/@me` with `Authorization: {token}`
On 200, it's a valid user token
On 401, it's an invalid token.

The code published here is almost certainly stealing any tokens that are being submitted. Just write your own small script to do the things like above to verify a token. No "queue" or "api limits", and no getting ur token stolen

**Comment by GuFFy12** [comment]
If you want code with such requests, use the previous versions of my checker. Why am I using a server? Firstly, these are the proxies that I buy for processing. Secondly, the server is used to connect other services via api. Let's process logs from a token logger via api or make a website or a telegram bot to check tokens. If you really want to accuse someone of stealing tokens, there are other closed source token checker services at the top of the github. Well, let me remind you: if you are afraid that this is a token thief, just do not use it.

PS: Your requests for validating tokens are not accurate. You need to make 1 more request to the discord service to verify the token.

https://discord.com/api/v9/users/@me/billing/payment-sources
tokenPayments.status === 200 - status = "valid"
else status="unverified"
